//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotDogLover.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.HotDogs = new HashSet<HotDog>();
        }
    
        public decimal ProfileID { get; set; }
        public string Name { get; set; }
        public string Bio { get; set; }
        public Nullable<decimal> HotDogID { get; set; }
        public string Picture { get; set; }
    
        public virtual ICollection<HotDog> HotDogs { get; set; }
    }
}
